version: '3.7'

services:

  database:
    build: ./database
    env_file: ./.env
    environment:
      - POSTGRES_USER=postgres
      # - POSTGRES_AUTH_METHOD=trust
    volumes:
      - ./database/base:/var/lib/postgresql/data

    restart: unless-stopped

  pgadmin:
    build: ./pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file: ./.env
    # ports:
    #   - "8080:8080"
    depends_on:
      - database
    restart: unless-stopped
    

  web_dev:
    build: ./web/dev
    env_file: ./.env
    environment:
      - BASE_URL=https://$HOSTNAME
    volumes:
      - $HOME/Boilerplate/web_dev:/home/web/srcs
    ports:
      - "3000:3000" # for dev only
    #   - "5555:5555" # for dev only
    restart: unless-stopped

  web_prod:
    build: ./web/prod
    env_file: ./.env
    environment:
      - BASE_URL=http://$HOSTNAME:3000
    volumes:
      - $HOME/Boilerplate/web_prod:/home/web/srcs
    # ports:
    #   - "8000:8000" # for dev only
    restart: unless-stopped

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt


networks:
  default:
    external: true
    name: network_reverseproxy

volumes:
  pgadmin-data:


