version: '3.7'

services:

  database:
    build: ./database
    container_name: database
    env_file: ./.env
    environment:
      - POSTGRES_USER=postgres
    cap_add:
      - NET_ADMIN
    volumes:
      - ./database/base:/var/lib/postgresql/data

    restart: unless-stopped

  pgadmin:
    build:
      context: .
      dockerfile: ./pgadmin/Dockerfile
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file: ./.env
    container_name: pgadmin
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    depends_on:
      - database
    restart: unless-stopped
    

  web_dev:
    build: ./web/dev
    container_name: web_dev
    env_file: ./.env
    environment:
      - BASE_URL=http://$HOSTNAME:3000
      - DEV=true
    volumes:
      - $HOME/Boilerplate/web_dev:/home/web/srcs
    ports:
      - "3000:3000" # for dev only
      # - "5555:5555" # for dev only
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  web_prod:
    build: ./web/prod
    env_file: ./.env
    container_name: web_prod
    environment:
      - BASE_URL=https://$HOSTNAME
      - DEV=false
    volumes:
      - $HOME/Boilerplate/web_prod:/home/web/srcs
    # ports:
    #   - "8000:8000" # for dev only
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt


networks:
  default:
    external: true
    name: network_reverseproxy

volumes:
  pgadmin-data:


